# Generated by Django 3.1.2 on 2020-10-11 03:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, unique=True, verbose_name='IP地址')),
                ('user', models.CharField(default='admin', max_length=128, verbose_name='用户名')),
                ('alias', models.CharField(blank=True, max_length=128, null=True, verbose_name='主机别名')),
                ('rsa_key', models.TextField(blank=True, null=True, verbose_name='RSA 私钥')),
                ('rsa_pub', models.TextField(blank=True, null=True, verbose_name='RSA 公钥')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建于')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新于')),
            ],
            options={
                'verbose_name': '客户机',
                'verbose_name_plural': '客户机管理',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineTaskFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=128, verbose_name='')),
                ('timestamp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MachineStatus',
            fields=[
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='status', serialize=False, to='tasks.machine')),
                ('online', models.SmallIntegerField(choices=[(1, '在线'), (0, '不在线')], default=1, verbose_name='是否在线')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建于')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新于')),
            ],
            options={
                'verbose_name': '主机状态',
                'verbose_name_plural': '主机状态查看',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='C:\\report\\', help_text='举例 C:\\report\\ -- 远程客户机上的绝对路径', max_length=255, verbose_name='任务文件夹')),
                ('prefix', models.CharField(default='EVT', help_text='举例 C:\\report\\ 下的成对的文件是 EVT2020091801.csv 和 2020091801.csv， 填写 EVT', max_length=32, verbose_name='')),
                ('period', models.PositiveIntegerField(help_text='每隔多少分钟执行一次任务', validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(1)], verbose_name='周期（分钟）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建于')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新于')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_ls', to='tasks.machine')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务管理',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '执行中'), (1, '成功'), (2, '失败')], default=0, verbose_name='任务状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建于')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新于')),
                ('file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='tasks.machinetaskfile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_ls', to='tasks.synctask')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='machinetaskfile',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.synctask'),
        ),
    ]
