# Generated by Django 3.1.2 on 2020-10-11 08:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['-created_at', '-updated_at'], 'verbose_name': '客户机', 'verbose_name_plural': '主机管理'},
        ),
        migrations.AlterModelOptions(
            name='machinestatus',
            options={'ordering': ['-created_at', '-updated_at'], 'verbose_name': '主机状态', 'verbose_name_plural': '在线监控'},
        ),
        migrations.AlterModelOptions(
            name='machinetaskfile',
            options={'ordering': ['-created_at', '-updated_at'], 'verbose_name': '任务文件', 'verbose_name_plural': '文件监视'},
        ),
        migrations.AlterModelOptions(
            name='syncjob',
            options={'ordering': ['-created_at', '-updated_at'], 'verbose_name': '同步记录', 'verbose_name_plural': '任务日志'},
        ),
        migrations.AlterModelOptions(
            name='synctask',
            options={'ordering': ['machine', '-created_at', '-updated_at'], 'verbose_name': '任务', 'verbose_name_plural': '任务管理'},
        ),
        migrations.AddField(
            model_name='machinetaskfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建于'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machinetaskfile',
            name='processed',
            field=models.SmallIntegerField(choices=[(0, '没有'), (1, '完成')], default=0, verbose_name='进一步处理'),
        ),
        migrations.AddField(
            model_name='machinetaskfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新于'),
        ),
        migrations.AlterField(
            model_name='machinestatus',
            name='machine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='status', serialize=False, to='tasks.machine', verbose_name='主机'),
        ),
    ]
