# Generated by Django 3.1.2 on 2020-10-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201011_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinetaskfile',
            old_name='processed',
            new_name='is_processed',
        ),
    ]
