# Generated by Django 3.1.2 on 2020-10-11 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20201012_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinetaskfile',
            name='file',
            field=models.TextField(verbose_name='相关文件名称'),
        ),
        migrations.AlterField(
            model_name='machinetaskfile',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_records', to='tasks.synctask', verbose_name='所属任务'),
        ),
    ]
