# Generated by Django 3.1.2 on 2020-10-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20201012_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='synctask',
            name='is_active',
            field=models.PositiveSmallIntegerField(choices=[(1, '已批准'), (0, '已停止')], default=1, verbose_name='任务状态'),
        ),
    ]
