# Generated by Django 3.1.2 on 2020-11-03 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_synctask_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synctask',
            name='is_active',
            field=models.PositiveSmallIntegerField(choices=[(1, '已批准'), (0, '已停止')], default=1, help_text='改变状态时，当前正在开展的任务不受影响，下一轮任务才会受影响', verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='synctask',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_ls', to='tasks.machine', verbose_name='所属主机'),
        ),
        migrations.AlterField(
            model_name='synctask',
            name='prefix',
            field=models.CharField(default='EVT', help_text='（实际上没有用这个参数， 默认就好）举例 C:\\report\\ 下的成对的文件是 EVT2020091801.csv 和 2020091801.csv， 填写 EVT', max_length=32, verbose_name=''),
        ),
    ]
